name: CI/CD for Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run sshpass commands
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: 51.222.111.183
        user: root
        pass: ${{ secrets.SSH_PASSWORD }}
        run: |
          cd /home/ubuntu/backend
          git pull origin master
          cd /home/ubuntu/
          docker-compose down
          docker-compose up --build 
